openapi: 3.2.0
info:
  title: Aquabyte API Documentation Lice API
  description: '# Aquabyte Public API


    To use our API you must be issued an API key.'
  version: v3.1
servers:
- url: /v3
- url: https://api.aquabyte.ai/v3
  description: Aquabyte API Server
tags:
- name: lice
  description: Lice APIs
paths:
  /liceCount:
    get:
      tags:
      - lice
      summary: Lice count for one or more pens
      operationId: get_pen_lice_count_liceCount_get
      parameters:
      - name: penId
        in: query
        required: true
        schema:
          type: string
          description: penId to query. Use "all" to query all pens
        description: penId to query. Use "all" to query all pens
      - name: fromDate
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          description: (optional) from date. Default is 7 days before toDate
        description: (optional) from date. Default is 7 days before toDate
      - name: toDate
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          description: (optional) to date (inclusive). Default is today
        description: (optional) to date (inclusive). Default is today
      - name: nextToken
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: (optional) token to fetch the next batch of result
        description: (optional) token to fetch the next batch of result
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aqua_api__paginator__append_next_token___locals___Wrapped__3'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input: {}
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    LiceCount:
      properties:
        penId:
          type: string
        date:
          type: string
          format: date
        sampleSize:
          type: number
          description: Number of samples used for estimating lice counts
        adultFemale:
          anyOf:
          - type: number
          - type: 'null'
          description: Average adult female lice per fish
        adultFemaleConverted:
          anyOf:
          - type: number
          - type: 'null'
          description: Average adult female lice (converted) per fish
        mobile:
          anyOf:
          - type: number
          - type: 'null'
          description: Average mobile lice per fish
        mobileConverted:
          anyOf:
          - type: number
          - type: 'null'
          description: Average mobile lice (converted) per fish
        caligus:
          anyOf:
          - type: number
          - type: 'null'
          description: Average caligus lice per fish
      type: object
      required:
      - penId
      - date
      - sampleSize
      - adultFemale
      - adultFemaleConverted
      - mobile
      - mobileConverted
      - caligus
      title: LiceCount
    aqua_api__paginator__append_next_token___locals___Wrapped__3:
      properties:
        liceCount:
          items:
            $ref: '#/components/schemas/LiceCount'
          type: array
        nextToken:
          anyOf:
          - type: string
          - type: 'null'
          description: If this is null, the result set is complete. If not null, fetch the next batch of result by passing this token to the next request.
      type: object
      required:
      - liceCount
      title: Wrapped
