openapi: 3.2.0
info:
  title: Aquabyte API Documentation Sites API
  description: '# Aquabyte Public API


    To use our API you must be issued an API key.'
  version: v3.1
servers:
- url: /v3
- url: https://api.aquabyte.ai/v3
  description: Aquabyte API Server
tags:
- name: Sites
paths:
  /sites:
    get:
      summary: Retrieve all sites and pens details
      description: Retrieve all available sites and pens in each site
      operationId: get_sites_sites_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SitesResponse'
      tags:
      - Sites
  /sites/{siteId}:
    get:
      summary: Retrieve site and pens details of {siteId}
      description: Retrieve all available sites and pens in each site
      operationId: get_sites_siteId_sites__siteId__get
      parameters:
      - name: siteId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SitesResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Sites
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input: {}
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      type: object
      title: HTTPValidationError
    SitesResponse:
      properties:
        sites:
          items:
            $ref: '#/components/schemas/Site'
          type: array
      type: object
      required:
      - sites
      title: SitesResponse
    Pen:
      properties:
        id:
          type: string
        name:
          type: string
        penCode:
          anyOf:
          - type: string
          - type: 'null'
        isActive:
          type: boolean
        external_id:
          anyOf:
          - type: string
          - type: 'null'
          title: External Id
          description: The corresponding id from data integration
      type: object
      required:
      - id
      - name
      - penCode
      - isActive
      title: Pen
    Site:
      properties:
        id:
          type: string
        name:
          type: string
        governmentSiteNumber:
          anyOf:
          - type: integer
          - type: 'null'
        external_site_id:
          anyOf:
          - type: string
          - type: 'null'
          title: External Site Id
          description: The corresponding site id from data integration
        pens:
          items:
            $ref: '#/components/schemas/Pen'
          type: array
      type: object
      required:
      - id
      - name
      - governmentSiteNumber
      - pens
      title: Site
